tago-io/sdk-js

src/modules/Account/Dashboards.ts
src/modules/Account/dashboards.types.ts

This PR adds the functionality to fetch the related analysis of a dashboard from the API.

feat: add listing a dashboard's related analysis

---

__tests__/Dictionary/applyToString.ts
__tests__/Dictionary/parseExpression.ts
src/modules/Dictionary/Dictionary.ts

This PR fixes an issue where the Dictionary attempted to parse `#something#` when it's the entire string because of the optimization on the splitting checking only for # at the beginning and the end of the split part of a string.
The fix adds a check for the split when parsing an expression to return null if the split RegEx did not match, which then makes `applyToString` simply use the original string instead of crashing when accessing an index that does not exist.
Example: a string like `"#something# test"` would not cause issues because the RegEx splitter would return `["#something# test"]`, and then when checking each item in the split array this one would not start and end with #. However, when the entire string is `#something#` the splitter does not find a RegEx and the split array …

fix: dictionary parsing values enclosed in hashtags

---

__tests__/Dictionary/applyToString.ts
src/modules/Dictionary/Dictionary.ts

There are at least two cases where `Dictionary.applyToString()` will accept values that are not strings (or `null`/`undefined`), one can be from using the SDK in a JS file which won't have type checking, the other would be passing the Dictionary instance without typing the parameter like this:
```ts
async function applyDictionary(value, dictionary) {
return dictionary.applyToString(value);
}
```
This PR adds a safeguard in case `applyToString` receives anything other than a string as a value.

fix: better handle non string values on applyToString

---

src/modules/Migration/Migration.ts

"virtualization_layer" is a sub type for compose widget that is not mapped by Migration.

[SDK-12] New compose sub type not mapped by Migration

---

src/modules/Migration/icon.ts

The old migration was done by a flag on the Dashboard structure. If ```dashboard.background.isMigrate``` you should import always the new Widget’s component.
The new migration now checks each widget, if it is OLD converts on the new structure and import the new Widget’s component.
The following client complain that his Icon’s lost the custom color and conditions, this happens because his structure is a mix of old and new.
[Client community post.](https://community.tago.io/t/widget-losing-customization/1259)
[Dashboard template.
](https://admin.tago.io/template/61491764683cae001898701d)

feat: sdk-13 migration icon widget mix structure

---

src/modules/Migration/cylinder.ts

In the Cylinder widget, the color condition priority was bottom-up, and the new is top-bottom.
The above conditions should be converted to this following order:

fix: cylinder color conditions sdk-14

---

src/modules/Account/Profile.ts
src/modules/Account/profile.types.ts

AuditLogCreate will create the query for the logs.
AuditLogQuery will retrieve the logs for a given queryId. The status can be "Complete" or "Running" if still searching for the logs.

feat: Added auditLogQuery and auditLogCreate

---

package-lock.json
package.json
src/common/common.types.ts
src/modules/Device/Device.ts
src/modules/Device/device.types.ts

This PR fixes data types and creates a separate one for `DataEdit` (for the `PUT` request on `/data`) and `DataCreate` (for the `POST` request on `/data`). These types will also be used in new routes.

fix: edit route and data type fixes [SDK-24]

---

src/modules/Account/Profile.ts
src/modules/Account/profile.types.ts

This PR adds support for fetching daily and monthly usage statistics. The options now have a secondary type for fetching monthly/daily statistics.

feat: add support for monthly and daily usage statistics [SDKJS-29]

---

src/modules/Resources/Devices.ts

Fixes issue in the devices.listStream where the filter object was not being copy correctly to the list method

fix: listStream wrong filter object

---

src/modules/Utils/router/service.ts

This pull request refactors the router service to include additional conditions for device and user list identifiers. The `whenDeviceListIdentifier` and `whenUserListIdentifier` methods have been updated to check for the presence of the button ID in the scope array. This ensures that the router service functions correctly when triggered by an input widget.

Refactor router service to include additional conditions for device and user list identifiers

---

src/modules/Resources/Buckets.ts
src/modules/Resources/Devices.ts
src/modules/Resources/TagoCores.ts
src/modules/Resources/devices.types.ts

PR based on #111 (branch: `sse_others`)
Fixes:
- Fixing missing properties in `DeviceInfo` and type union over `type`
- Marking methods in `Resources.buckets` as deprecated
- Adding `amount` to `Resources.devices` to get the data amount stored in the Device

feat: deprecate buckets, fix DeviceInfo type, add data amount to Device resource

---

src/modules/Services/MQTT.ts

Deprecated bucket field on MQTT call service, now is "device"

Deprecated bucket field on MQTT call service

---

src/modules/Network/Network.ts

This pull request adds a new method to the Network class called `publishToRelay()`. This method allows users to publish a message to the MQTT relay. The method takes in various options such as the topic, message, quality of service level, bucket, retain flag, and device. It then sends a request to the server to publish the message. This new method enhances the functionality of the Network class and provides users with more flexibility when working with MQTT relay.

Add MQTT relay publishing method

---

src/infrastructure/apiSSE.ts
src/modules/Analysis/Analysis.ts

Support multi-channel connections on SSE, which is in a newer version of the SSE service.
This PR **changes the function signature** for `openSSEListening` for a few reasons:
- Support a single channel or multiple channels as the first parameter (URL is built differently for multi-channel)
- Move `token`/`region` to second parameter since it's decoupled from the channels
Type definitions show these changes in the editor properly in case of updating from a previous version.
```ts
const single = await openSSEListening(
{ channel: "device_inspector", resource_id: "1234" },
{ token: "my-token", region: "usa-1" },
);
const multi = await openSSEListening(
[
{ channel: "device_inspector", resource_id: "1234" },
{ channel: "device_inspector", resource_id: "5678" },
{ channel: "ui" },
],
{ token: …
```

feat: support multichannel SSE connections

---

src/modules/Resources/Devices.ts
src/modules/Resources/devices.types.ts

Add new route to retrieves a list with all devices from profile filtered by serial and network.

Created a route to get a list of devices by serial and network id

---

src/modules/Device/device.types.ts

This PR moves the `details` parameter to `DataQueryBase` so it can be used in different data queries, such as `last_insert` and so on.

fix: move details parameter to DataQueryBase

---

src/modules/Analysis/analysis.types.ts
src/modules/Device/device.types.ts
src/modules/Dictionary/Dictionary.ts
src/modules/Resources/Account.ts
src/modules/RunUser/RunUser.ts
src/modules/Utils/getAPIVersion.ts
src/regions.ts

- Add support for the new Europe region (`eu-w1`)
- Rename `usa-1` to `us-e1`, with fallback when passing `usa-1`
- Add the `region` parameter to methods that didn't have support for it

feat: add support for Europe region [SDKJS-50]

---

src/common/common.types.ts
src/modules/Resources/Dashboard.Widgets.ts

Fix regression in `deleteData` method that made it only delete 1 record from 1 device.
Current version of SDK without reverting this will break Production. 
It's marked as breaking just to revert the breaking change.

fix: regression in Dashboard API to delete data [SDKJS-55]

---

package-lock.json
package.json
src/common/TagoIOModule.ts
src/infrastructure/apiRequest.ts
src/infrastructure/apiRequestFetch.test.ts
src/modules/Resources/Files.test.ts
src/modules/Resources/Files.ts

- Update logic for multipart uploads to work with `fetch`
- Remove `form-data` dependency
- `FormData` available on Node since 18
- Remove automatic handling of `Buffer` as input for uploads
- Added example on how to create `Blob` from `Buffer`

fix: rewrite logic in Files module with native FormData + fetch
