tago-io/sdk-js

src/modules/Device/device.types.ts

Changing to get bucket as JSON instead of string

fixed device.info

---

src/modules/Account/run.types.ts

Run notification was missing some features in the interface.

Added: NotificationButtons interface to run notification

---

src/modules/Account/Dashboard.Widgets.ts

Added proper response for widgets.create

Added: response interface for widget create

---

src/modules/RunUser/runUser.types.ts

feat: added options to run user interface

---

src/modules/Analysis/Analysis.ts

feat: handle callstack error to TagoIO

---

package-lock.json
package.json
src/modules/Account/Notifications.ts
src/modules/Account/Run.ts
src/modules/Account/notifications.types.ts
src/modules/Account/run.types.ts
src/modules/RunUser/RunUser.ts
src/modules/Services/Notification.ts

Support for [notification/refactoring](https://github.com/tago-io/core/pull/587) of Core

CORE-90 updated notification interfaces and new routes

---

src/modules/Account/Account.ts
src/modules/Account/account.types.ts
src/modules/Account/run.types.ts
src/modules/RunUser/RunUser.ts
src/modules/RunUser/runUser.types.ts

Support for branch [feature/OTP/CORE-98](https://github.com/tago-io/core/pull/591) of CORE

feat: added OTP methods

---

src/modules/Account/Dashboard.Widgets.ts
src/modules/Account/dashboards.types.ts

Support for branch [feat/resourceWidget/CORE-111](https://github.com/tago-io/core/pull/596) from CORE.

feat: added resource widget route and editData route

---

package-lock.json
package.json
src/modules/Account/TagoCores.ts

This PR adds the `.delete` call to account.tagocores.

SDK-21: Delete function for tcore

---

src/modules/Account/Notifications.ts

* Added route to create notifications

feat: added sdk route to create dev notification

---

src/modules/Account/TagoCores.ts
src/modules/Account/tagocore.types.ts

This PR adds the TCore cluster functionality to the SDK. It also improves the TCore functionality by adding two new fields.

[SDK-25] TCore cluster

---

src/modules/Services/PDF.ts

fix: creating pdf return type

---

src/modules/Utils/sendDownlink.test.ts
src/modules/Utils/sendDownlink.ts

Fixed an error when user uses Utils.sendDownlink and receives an error in JSON format.

fixed JSON error message and added test

---

src/modules/Device/Device.ts
src/modules/Device/device.types.ts
src/modules/Resources/Devices.ts
src/types.ts

Fixing streaming data to be able to cancel process, today is a bug, when stop the `for await ` the streaming is not stopping.

Fixing streaming data functions

---

src/modules/Device/device.types.ts

Add new query 'conditional' and 'aggregate' to getData.

added query conditional and aggregate to getData

---

src/modules/Device/Device.ts
src/modules/Device/device.types.ts

fix: some incorrect updated types

---

src/modules/Resources/Resources.ts
src/modules/Resources/Secrets.ts
src/modules/Resources/Tags.ts
src/modules/Resources/secrets.type.ts

feat: created secrets routes

---

__tests__/Utils/analysisRouter.ts

Test the Device/user List indetifier

Add new conditions for analysis router tests

---

src/modules/Resources/actions.types.ts

Adding the new type for `trigger_when_unlock`, which define if the Action should be triggered when the unlock conditions are met.
...

feat: adding new type for action [SDKJS-42]

---

src/modules/Resources/run.types.ts

This pull request adds a new interface called UserOptions to the UserCreateInfo class. The UserOptions interface includes additional properties that can be used to customize user creation.

Add UserOptions interface to UserCreateInfo

---

src/modules/Services/MQTT.ts

update mqtt.publish type

---

src/infrastructure/apiRequest.ts
src/modules/Resources/Buckets.ts

Remove the bucket.export function that has been deprecated years ago.

removed export route from sdk

---

package-lock.json
package.json
src/modules/Services/AWS-SQS.ts
src/modules/Services/Email.ts
src/modules/Services/SMTP.ts
src/modules/Services/Sendgrid.ts
src/modules/Services/Services.ts
src/modules/Services/Twillio.ts

This PR introduces new service modules and updates existing ones to enhance the functionality of our TagoIO SDK.
- AWS-SQS: Adds support for sending messages to Amazon SQS.
- SMTP: Introduces a new email service using SMTP integration.
- Twilio: Adds capability to send SMS messages using Twilio.
- Services: Integrates new modules (AWS-SQS, SMTP, Twilio) and reorganizes imports.
- Email: Exports additional types for better type checking.

Support to new Action Services through SDK

---

src/modules/Resources/actions.types.ts

Added a new type of trigger for actions

SRV-507 Add Action Resource for Usage Alert

---

src/modules/Resources/actions.types.ts

Added a new type of trigger for actions

SRV-320 Create new Action type 'Geofence'

---

src/modules/Services/Services.ts
src/modules/Services/Twilio-Whatsapp.ts

Add new integration with Twilio for Whatsapp Message

SRV-599 Twilio Whatsapp

---

src/modules/Resources/TagoCores.ts
src/modules/Resources/tagocore.types.ts

fix: removing cluster integration [SDKJS-46]

---

src/modules/Resources/Devices.ts
src/modules/Resources/devices.types.ts

This PR adds the calls to the device data backup & restore APIs.
Chunk copy is marked as deprecated.

feat: add device data backup and restore APIs

---

package-lock.json
package.json

update axios lib

---

package-lock.json
package.json
src/infrastructure/apiSSE.ts
src/modules/Analysis/Analysis.ts

- Updated Eventsource lib;
- Added keep-alive to handle Realtime server connection.

updated eventsource lib and add keep-alive rule

---

src/modules/Resources/Files.ts
src/modules/Resources/files.types.ts

feat: adding blueprint device params to upload files [SDK-JS-43]

---

src/modules/Services/Twillio.ts

Created support for MessaginServiceSID and FROM ID to twilio SMS

SRV-643 Add MessageSID and FromID support to Twilio/Sendgrid
